import type { Command, DeepReadonly, FateChoice, Feat } from '../core/types';

export interface TranscriptEntry { targetTick: number; command: Command }
export type CoreRecipe = 'journey' | 'defeat' | 'resident-loss' | 'casualties' | 'combat-input' | 'shield' | 'orders' | 'preparation' | 'replay';
export interface Scenario {
 id: string;
 seed: number;
 reset: 'Simulation.create(seed)';
 path: string;
 execution: 'core-and-browser' | 'browser' | 'document';
 recipe?: CoreRecipe;
 late?: boolean;
 fate?: FateChoice;
 feat?: Feat;
 checkpoints: readonly string[];
 transcript: readonly TranscriptEntry[];
 transcriptPolicy: string;
 remaining: readonly string[];
}

const enter: readonly TranscriptEntry[] = [
 { targetTick: 1, command: { type: 'speed', speed: 4 } },
 { targetTick: 1, command: { type: 'travel', point: { x: 0, z: 0 } } },
];
const generated = 'Record all subsequent public commands with exact target ticks; replay the persisted transcript without running the controller. No state mutation after reset.';
const browser = 'Browser harness must record real inputs, load results and target-tick commands; the core runner does not execute or pass this path.';

export const SCENARIOS: DeepReadonly<Scenario[]> = [
 { id: 'SCN-01-FULL-EARLY-RELEASE', seed: 1101, reset: 'Simulation.create(seed)', execution: 'core-and-browser', recipe: 'journey', fate: 'Release', feat: 'Rapid Guard', path: 'New campaign → two Troops → Accept → bridge victory → Release Agent and ordinary survivors → Rapid Guard → Safe settlement', checkpoints: ['CP-SPEC-END-TO-END', 'CP-FLOW-CONTRACT', 'CP-FLOW-EARLY', 'CP-REL-RELEASE'], transcript: enter, transcriptPolicy: generated, remaining: ['Recorded complete-run elapsed real time with input provenance and recording limits; no duration bound', 'Representative melee and leadership quality', 'Offer, Journal, setup, transition and changed-settlement visual artifacts'] },
 { id: 'SCN-02-FULL-EARLY-CAPTURE', seed: 1102, reset: 'Simulation.create(seed)', execution: 'core-and-browser', recipe: 'journey', fate: 'Capture', feat: 'Rapid Stamina', path: 'Bridge victory → Capture Agent and ordinary survivors → Rapid Stamina → Safe settlement', checkpoints: ['CP-REL-CAPTURE'], transcript: enter, transcriptPolicy: generated, remaining: ['Choice, summary and Journal PNG artifacts'] },
 { id: 'SCN-03-FULL-EARLY-EXECUTE', seed: 1103, reset: 'Simulation.create(seed)', execution: 'core-and-browser', recipe: 'journey', fate: 'Execute', feat: 'Rapid Attack', path: 'Bridge victory → Execute Agent and ordinary survivors → Rapid Attack → Safe settlement', checkpoints: ['CP-REL-EXECUTE'], transcript: enter, transcriptPolicy: generated, remaining: ['Choice, summary and Agent reaction PNG artifacts'] },
 { id: 'SCN-04-FULL-LATE-VICTORY', seed: 1201, reset: 'Simulation.create(seed)', execution: 'core-and-browser', recipe: 'journey', late: true, fate: 'Release', feat: 'Rapid Guard', path: 'Accept → Leave → deadline passes while travelling → center battle without setup → victory → survivor choices → Feat → Damaged settlement', checkpoints: ['CP-SPEC-END-TO-END', 'CP-FLOW-LATE'], transcript: enter, transcriptPolicy: generated, remaining: ['Recorded complete-run elapsed real time with input provenance and recording limits; no duration bound', 'Boundary-entry WebM and damaged-return PNG', 'Recorded unpaused battle real time; no duration bound'] },
 { id: 'SCN-05-BAND-DEFEAT', seed: 1202, reset: 'Simulation.create(seed)', execution: 'core-and-browser', recipe: 'defeat', path: 'New campaign with no recruited Troops → bridge battle → all Band members defeated before raiders → no fate or Feat choice → Failed/Damaged return', checkpoints: ['CP-SPEC-END-TO-END', 'CP-FLOW-DEFEAT', 'CP-REL-FAILURE'], transcript: enter, transcriptPolicy: generated, remaining: ['Defeat transition WebM and changed reactions PNG', 'Recorded complete-run elapsed real time with input provenance and recording limits; no duration bound'] },
 { id: 'SCN-06-RESIDENT-LOSS', seed: 1203, reset: 'Simulation.create(seed)', execution: 'core-and-browser', recipe: 'resident-loss', path: 'Hold both Command groups away from the residents → player evades without attacking → last resident killed while Band and raiders remain active → immediate Failed/Damaged summary → changed settlement', checkpoints: ['CP-FLOW-DEFEAT', 'CP-SPEC-END-TO-END'], transcript: enter, transcriptPolicy: generated, remaining: ['Simultaneous resident-loss/victory priority boundary', 'Defeat transition WebM'] },
 { id: 'SCN-07-COMBAT-SECTOR-MATRIX', seed: 1301, reset: 'Simulation.create(seed)', execution: 'core-and-browser', recipe: 'combat-input', path: 'Bridge battle → four sword previews, revisions and release → wind-up feint → committed recovery and misses; full acceptance additionally requires staff paths, multi-target hit and both guard outcomes', checkpoints: ['CP-COMBAT-INPUT', 'CP-COMBAT-GUARD', 'CP-COMBAT-DAMAGE'], transcript: enter, transcriptPolicy: generated, remaining: ['Staff four-sector and multi-target damage matrix', 'Matched and mismatched guard damage/recoil matrix', 'Movement multipliers, sector PNGs and combat WebMs'] },
 { id: 'SCN-08-SHIELD-EXHAUSTION', seed: 1302, reset: 'Simulation.create(seed)', execution: 'core-and-browser', recipe: 'shield', path: 'Bridge battle → shield toggle/hold → continuous drain → zero-stamina stagger → release → delayed regeneration → re-enable at 12', checkpoints: ['CP-COMBAT-GUARD'], transcript: enter, transcriptPolicy: generated, remaining: ['Every incoming sector blocked without attacker recoil', 'Shield PNG and exhaustion WebM'] },
 { id: 'SCN-09-CASUALTY-MATRIX', seed: 1303, reset: 'Simulation.create(seed)', execution: 'core-and-browser', recipe: 'casualties', path: 'Deploy Troops ahead of the separated Band → actual Troop casualties → concealed Journal roster and inactive Command-group rejection → player/Companion counterattack → victory reveals true losses → exact surviving Band persists in settlement snapshot', checkpoints: ['CP-COMBAT-CASUALTY', 'CP-COMMAND-GROUPS', 'CP-SPEC-END-TO-END'], transcript: enter, transcriptPolicy: generated, remaining: ['Complete six-role casualty matrix; this recipe checks observed events, not unobserved role/outcome combinations', 'Both sides of the seeded threshold in one linked acceptance run; alternate-seed core regression is separate evidence', 'Indistinguishable battle bodies PNG and post-battle reveal PNG'] },
 { id: 'SCN-10-COMMAND-GROUPS', seed: 1401, reset: 'Simulation.create(seed)', execution: 'core-and-browser', recipe: 'orders', path: 'Four Troops deploy → independently placed Hold markers and rejected river placement → both groups physically follow the moved player → Engage advance → actual target loss and next-tick nearest-threat selection for both groups', checkpoints: ['CP-COMMAND-GROUPS', 'CP-COMMAND-AI'], transcript: enter, transcriptPolicy: generated, remaining: ['Off-screen marker PNG', 'Follow/Hold return after target loss and resident flee evidence', 'Readable pressure/formation WebM'] },
 { id: 'SCN-11-PREPARATION-TRAVEL', seed: 1501, reset: 'Simulation.create(seed)', execution: 'core-and-browser', recipe: 'preparation', path: 'Recruit sequentially zero through four → reject duplicate/fifth recruitment → all speeds and pause → leave, moving member-days and zero-Provisions travel', checkpoints: ['CP-FLOW-CONTRACT', 'CP-PREP-RECRUIT', 'CP-PREP-PROVISIONS'], transcript: enter, transcriptPolicy: generated, remaining: ['Browser keys, Journal and pause/speed artifacts', 'Browser save/reload at fractional provision remainder (core regression exercises restoration)'] },
 { id: 'SCN-12-FEAT-MATRIX', seed: 1601, reset: 'Simulation.create(seed)', execution: 'core-and-browser', recipe: 'journey', fate: 'Release', feat: 'Rapid Guard', path: 'Actual victory → pending fate confirmation → one Feat → reject repeated choice; compare all three action modifiers in separate valid runs', checkpoints: ['CP-FEAT'], transcript: enter, transcriptPolicy: generated, remaining: ['All three before/after timing comparisons including shield 0.16s, guard 0.20s, attack ×0.80 and stamina 30/s after 1.2s', 'Feat PNG and timing WebM'] },
 { id: 'SCN-13-SAVE-RESTORE', seed: 1701, reset: 'Simulation.create(seed)', execution: 'browser', path: 'Save and load Overworld/settlement in three manual slots plus autosave → launch recovery → unsafe boundary rejection → confirmed delete/reset', checkpoints: ['CP-SAVE-BOUNDARY', 'CP-SAVE-RESTORE'], transcript: enter, transcriptPolicy: browser, remaining: ['Browser adapter rebuilding, autosave launch recovery and confirmations', 'Slot, enabled/disabled controls and restored Journal PNG; transition WebM', 'Core and fake-indexeddb regression tests are separate evidence, not this browser run'] },
 { id: 'SCN-14-SAVE-FAILURES', seed: 1702, reset: 'Simulation.create(seed)', execution: 'browser', path: 'Old/corrupt records → unavailable; storage denied/full → persistent failure with in-memory continuation → Retry recovery → confirmed deletion', checkpoints: ['CP-SAVE-FAILURE'], transcript: enter, transcriptPolicy: browser, remaining: ['Real browser failure state and confirmation PNGs', 'Fake-indexeddb fault tests do not establish browser UI behavior'] },
 { id: 'SCN-15-WEBGPU-STARTUP-LOAD', seed: 1801, reset: 'Simulation.create(seed)', execution: 'browser', path: 'Promised-row physical adapter success; independently fail secure context, adapter, device, fallback and Scene load before gameplay', checkpoints: ['CP-SUPPORT-GATE', 'CP-SUPPORT-LOAD'], transcript: enter, transcriptPolicy: browser, remaining: ['Real promised-row environment, gate order and load stage console records', 'Each unsupported/ready PNG and success/failure loading WebM'] },
 { id: 'SCN-16-WEBGPU-DEVICE-LOSS', seed: 1802, reset: 'Simulation.create(seed)', execution: 'browser', path: 'Active battle → real GPUDevice.destroy → loss → unchanged Simulation tick and no subsequent events → visible Reload → startup gates again', checkpoints: ['CP-DELIVERY-DEVICE-LOSS'], transcript: enter, transcriptPolicy: browser, remaining: ['Real device-loss event and reload on promised row', 'Device-loss transition WebM'] },
 { id: 'SCN-17-PERFORMANCE-BRIDGE', seed: 1803, reset: 'Simulation.create(seed)', execution: 'browser', path: 'Default two-Troop bridge battle on promised hardware → natural outcome → recorded unpaused real time and delivered frame intervals; no duration bound', checkpoints: ['CP-PERFORMANCE'], transcript: enter, transcriptPolicy: browser, remaining: ['Measured average ≤16.67ms and p95 ≤33.33ms', 'No below-30fps interval >1s', 'Recorded duration, input provenance and measurement limits; no artificial waiting, fake timing or core tick throughput substitutes'] },
 { id: 'SCN-18-PRESENTATION-AUDIO', seed: 1901, reset: 'Simulation.create(seed)', execution: 'browser', path: 'Settlement, attack preview, guard, Journal, battle casualties and kneeling fate → sector/material audio, ducking/fade → audio initialization failure/Retry', checkpoints: ['CP-UI-HUD', 'CP-UI-FATE', 'CP-AUDIO'], transcript: enter, transcriptPolicy: browser, remaining: ['Woodcut visual quality and minimal semantic HUD', 'Static PNGs after two stable rendered frames', 'Audible sector, ducking, fate fade and init-failure WebMs ≤8s'] },
 { id: 'SCN-19-DETERMINISTIC-REPLAY', seed: 2001, reset: 'Simulation.create(seed)', execution: 'core-and-browser', recipe: 'replay', fate: 'Release', feat: 'Rapid Guard', path: 'Generate a complete public-command bridge victory transcript → two clean resets → replay exact target ticks → compare command, checkpoint, event, random state and outcome hashes', checkpoints: ['CP-ARCH-DETERMINISM'], transcript: enter, transcriptPolicy: generated, remaining: ['Browser artifact-metadata determinism and platform adapter isolation beyond core frozen projections'] },
 { id: 'SCN-20-SPEC-AUDIT', seed: 0, reset: 'Simulation.create(seed)', execution: 'document', path: 'Run scripts/audit-spec.mjs --self-check against the unchanged normative document and requirements links', checkpoints: ['CP-SPEC-AUDIT'], transcript: [], transcriptPolicy: 'Document-only scenario: no gameplay transcript is applicable; run the document audit, not Simulation.', remaining: ['Document audit must be run independently; core runner does not mark it passed'] },
];

export const CHECKPOINTS = [
 'CP-SPEC-END-TO-END', 'CP-SUPPORT-GATE', 'CP-SUPPORT-LOAD', 'CP-FLOW-CONTRACT', 'CP-FLOW-EARLY', 'CP-FLOW-LATE', 'CP-FLOW-DEFEAT', 'CP-COMBAT-INPUT', 'CP-COMBAT-GUARD', 'CP-COMBAT-DAMAGE', 'CP-COMBAT-CASUALTY', 'CP-COMMAND-GROUPS', 'CP-COMMAND-AI', 'CP-REL-RELEASE', 'CP-REL-CAPTURE', 'CP-REL-EXECUTE', 'CP-REL-FAILURE', 'CP-FEAT', 'CP-PREP-RECRUIT', 'CP-PREP-PROVISIONS', 'CP-UI-HUD', 'CP-UI-FATE', 'CP-AUDIO', 'CP-ARCH-DETERMINISM', 'CP-SAVE-BOUNDARY', 'CP-SAVE-RESTORE', 'CP-SAVE-FAILURE', 'CP-DELIVERY-DEVICE-LOSS', 'CP-PERFORMANCE', 'CP-SPEC-AUDIT',
] as const;
export type CheckpointId = typeof CHECKPOINTS[number];
